### ISSUE TITLE
Query with specified condition.

### ISSUE THREAD

**Issue by SinDotBe** [simpleidserver/EFCore.Cassandra#3] opened 2020-05-18 13:53 UTC
In EFCore.Cassandra.Samples, This query 
` int k = 10;
  var d = dbContext.Applicants.Where(d => d.Decimal == k);`
encounters such an error:
`line 3:19 no viable alternative at character '_'`
thanks!

**Comment by simpleidserver** [comment] 2020-05-20 16:09
The problem is fixed in the branch "release/2.0.0".
We are doing some investigation to understand why it's not possible to filter on **GUID**.

**Comment by simpleidserver** [comment] 2020-05-21 18:12
The issue is fixed in the release 2.0.0.

**Closed as completed** 2020-05-31 10:31 UTC
Labels: bug

**Comment by SinDotBe** [comment] 2020-05-31 10:32
thanks a lot
