### ISSUE TITLE
Is it possible to create a keyspace while applying migrations?

### ISSUE THREAD

**Issue by pluskal** [simpleidserver/EFCore.Cassandra#10] opened 2020-10-30 11:53 UTC
When I try to apply migration or create a database using
```

using (var dbContext = new FakeDbContext())
        {
          dbContext.Database.Migrate();
// OR
          dbContext.Database.EnsureCreated();
        }
```
when a keyspace does not exist, I am getting an exception.

Would it make sense to extend the implementation of `DatabaseFacade` methods `EnsureCreated, Migrate` and async variants to create keyspace when it does not exist?

**Comment by simpleidserver** [comment] 2020-10-31 20:07
The issue is fixed in the branch "release/2.0.3".

**Closed as completed** 2020-11-02 06:40 UTC
Labels: bug
